# Generated by Django 5.2 on 2025-04-30 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cityname', models.CharField(blank=True, max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityWeatherCurrent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_dt', models.DateTimeField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('simple_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CityWeatherForecast',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_dt', models.DateTimeField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_min', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temp_max', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('simple_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('sunrise', models.DateTimeField(blank=True, null=True)),
                ('sunset', models.DateTimeField(blank=True, null=True)),
                ('pressure', models.IntegerField(blank=True, null=True)),
                ('humidity', models.IntegerField(blank=True, null=True)),
                ('temp_feels', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('detail_desc', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(blank=True, max_length=150, null=True, unique=True)),
                ('pwd_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('avatar_id', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('city_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserSession',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
