# Generated by Django 5.2 on 2025-05-08 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='detail_desc',
        ),
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='humidity',
        ),
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='pressure',
        ),
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='sunrise',
        ),
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='sunset',
        ),
        migrations.RemoveField(
            model_name='cityweatherforecast',
            name='temp_feels',
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='detail_desc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='humidity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='pressure',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='sunrise',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='sunset',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='temp_feels',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
