# Generated by Django 5.2 on 2025-05-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_cityweatherforecast_detail_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityweathercurrent',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cityweathercurrent',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
